### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by jhur628** [Dog-with-two-Gs/tenant-buddy#24]
- [x] Apartments
- [x] Building
- [x] Company
- [x] CycleType
- [x] DryLevel
- [x] DryerSetting
- [x] Employee
- [x] Machine
- [x] Reservation
- [x] Role
- [x] Tenant/User
- [x] WasherSettings
- [x] index

**Comment by AJones1200** [comment]
mgmt/company, apts, complex/bldg, employee, role & tenant models completed.

**Comment by kvs1995** [comment]
index.js and relationships completed.
